services:
    tms_like.manager.uri_like:
        class:     Tms\Bundle\LikeBundle\Manager\UriLikeManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]
        tags:
            - { name: rest.link, class: Tms\Bundle\LikeBundle\Entity\UriLike }
