Tms\Bundle\LikeBundle\Entity\UriLike:
    exclusion_policy: ALL

    properties:
        id:
            expose: true
            groups: [tms_rest.collection, tms_rest.item, tms_modelio]
        uri:
            expose: true
            groups: [tms_rest.collection, tms_rest.item, tms_modelio]
            serialized_name: uri
        userId:
            expose: true
            groups: [tms_rest.collection, tms_rest.item, tms_modelio]
            serialized_name: userId
        createdAt:
            expose: true
            groups: [tms_rest.item, tms_modelio]
            serialized_name: createdAt
