Tms\Bundle\LikeBundle\Entity\UrlLike:
    exclusion_policy: ALL

    properties:
        id:
            expose: true
            groups: [tms_rest.collection, tms_rest.item, tms_modelio]
        url:
            expose: true
            groups: [tms_rest.collection, tms_rest.item, tms_modelio]
            serialized_name: url
        userId:
            expose: true
            groups: [tms_rest.collection, tms_rest.item, tms_modelio]
            serialized_name: userId
        createdAt:
            expose: true
            groups: [tms_rest.item, tms_modelio]
            serialized_name: createdAt
